
1.	Write a Python Program to Add Two Matrices?

In [ ]:
import numpy as np
arr1 = [[1,2,3,4], [1,2,3,4]]
arr2 = [[1,2,3,4], [1,2,3,4]]
arr = np.add(arr1, arr2)
print(arr)

[[2 4 6 8]
 [2 4 6 8]]


2.	Write a Python Program to Multiply Two Matrices?

In [ ]:
import numpy as np
arr1 = [[1,2], [1,2]]
arr2 = [[3,4], [3,4]]
arr = np.matmul(arr1, arr2)
print(arr)

[[ 9 12]
 [ 9 12]]


3.	Write a Python Program to Transpose a Matrix?

In [1]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]
result = [[0,0,0],
         [0,0,0]]
for i in range(len(X)):
  for j in range(len(X[0])):
    result[j][i] = X[i][j]
for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [2]:
my_str = "My name is Dushyant Sharma"
words = [word.lower() for word in my_str.split()]
words.sort()
print("The sorted words are:")
for word in words:
   print(word)

The sorted words are:
dushyant
is
my
name
sharma


5.	Write a Python Program to Remove Punctuation From a String?

In [3]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = "Hello!!!, he said ---and went."
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char
print(no_punct)

Hello he said and went
